import type { Metadata } from 'next';
import './globals.scss';

import { Space_Mono } from 'next/font/google';

// Carga la fuente (puedes definir subsets, weights, etc.)
const spaceMono = Space_Mono({
  subsets: ['latin'],
  weight: ['400', '700'], // o 'variable' si prefieres
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${spaceMono.className}`}>{children}</body>
    </html>
  );
}
